# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home_Page.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtGui, QtWidgets




from PyQt5 import QtCore, QtGui, QtWidgets
from New_Window import Ui_New_Window
class Ui_MainWindow(object):
    def openWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_New_Window()
        self.ui.setupUi(self.window)
        self.window.show()
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.showMaximized()
        #MainWindow.setAutoFillBackground(True)
        MainWindow.setStyleSheet("background-image: url(hp.jpg)")
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setWeight(100)
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setIconSize(QtCore.QSize(25, 25))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        #self.centralwidget.setStyleSheet("background-image : url(https://images.unsplash.com/photo-1485796826113-174aa68fd81b?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=750&q=80)")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 80, 600, 41))
        font = QtGui.QFont("Cambria")
        font.setPointSize(14)
        font.setWeight(100)
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet("color: white;")
        #self.label.setColor(QColor(Qt.transparent))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(490, 130, 370, 61))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        font.setUnderline(False)
        self.label_2.setFont(font)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setStyleSheet("color: white;")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(445, 30, 431, 41))
        font = QtGui.QFont("Cambria")
        font.setPointSize(14)
        font.setWeight(100)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(False)
        self.label_3.setStyleSheet("color: white;")
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(380, 300, 601, 50))
        font = QtGui.QFont("Cambria")
        font.setPointSize(20)
        font.setWeight(100)
        font.setUnderline(False)
        self.label_5.setFont(font)
        self.label_5.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_5.setStyleSheet("color: red;")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(380, 370, 111, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setStyleSheet("color: white;")
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(380, 420, 250, 21))
        self.label_7.setAutoFillBackground(False)
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white;")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setGeometry(QtCore.QRect(380, 470, 250, 20))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white;")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setGeometry(QtCore.QRect(820, 370, 111, 31))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: white;")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setGeometry(QtCore.QRect(820, 410, 250, 31))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: white;")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setAutoFillBackground(False)
        self.label_11.setGeometry(QtCore.QRect(820, 440, 355, 31))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: white;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setGeometry(QtCore.QRect(820, 470, 250, 31))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setAutoFillBackground(False)
        self.label_13.setGeometry(QtCore.QRect(820, 500, 305, 31))
        font = QtGui.QFont("Cambria")
        font.setPointSize(16)
        font.setWeight(100)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setObjectName("label_13")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.clicked.connect(self.openWindow)
        self.pushButton.setGeometry(QtCore.QRect(600, 590, 131, 41))
        font = QtGui.QFont("Cambria")
        font.setPointSize(12)
        font.setWeight(100)
        font.setItalic(False)
        font.setUnderline(False)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("")
        self.pushButton.setStyleSheet("QPushButton""{""background-color : white;""}""QPushButton::pressed""{""background-color : aqua;""}")
        self.pushButton.setStyleSheet("color:white;")
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(620, 195, 111, 101))
        self.label_4.setTabletTracking(False)
        self.label_4.setStatusTip("")
        #self.label_4.setStyleSheet("image: url(:https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.static-contents.youth4work.com%2Funiversity%2FDocuments%2FColleges%2FcollegeLogo%2F20190606124332.png%3Fv%3D20190606124332&imgrefurl=https%3A%2F%2Fwww.university.youth4work.com%2Fsrcasw_shaheed-rajguru-college-of-applied-sciences-for-women&tbnid=gKzvlr9ms3piJM&vet=12ahUKEwiAyfzji7PsAhUKg2MGHT0OApkQMygAegUIARCoAQ..i&docid=VunbKYmw1w3SfM&w=104&h=111&q=shaheed%20rajguru%20college%20logo&ved=2ahUKEwiAyfzji7PsAhUKg2MGHT0OApkQMygAegUIARCoAQ);")
        self.label_4.setText("")
        #self.label_4.setPixmap(QtGui.QPixmap("logo.png"))
        self.label_4.setPixmap(QtGui.QPixmap("../Documents/sl5_files/logo.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setOpenExternalLinks(True)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 747, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "SHAHEED RAJGURU COLLEGE OF APPLIED SCIENCES FOR WOMEN"))
        self.label_2.setText(_translate("MainWindow", "     Department Of Computer Science"))
        self.label_3.setText(_translate("MainWindow", "SUMMER INTERNSHIP PROJECT"))
        self.label_5.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"justify\"><br/></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "\"FROM UNSTRUCTURED TO STRUCTRED DATA\""))
        self.label_6.setText(_translate("MainWindow", "Mentors :-      "))
        self.label_7.setText(_translate("MainWindow", "> Dr. Abha Jain"))
        self.label_8.setText(_translate("MainWindow", "> Ms Neha Gandhi"))
        self.label_9.setText(_translate("MainWindow", "Mentees :-"))
        self.label_10.setText(_translate("MainWindow", ">Aparajita (2018305)"))
        self.label_11.setText(_translate("MainWindow", ">Katyayani Raghuvanshi (2018327)"))
        self.label_12.setText(_translate("MainWindow", ">Seher Salim (2018342)"))
        self.label_13.setText(_translate("MainWindow", ">Shreya Shrivastava (2018346)"))
        self.pushButton.setText(_translate("MainWindow", "APPLICATION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
 
    stylesheet = """
    MainWindow {
        background-image: url("hp.jpg"); 
        background-repeat: no-repeat; 
        background-position: center;
    }
""" 
    app.setStyleSheet(stylesheet)
    app.setWindowIcon(QtGui.QIcon('logo.jpg'))
    MainWindow.setWindowIcon(QtGui.QIcon('logo.jpg'))
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

